# Ansible inventory generated by Terraform
# Date: ${timestamp()}

[bastion]
${bastion_fqdn} ansible_host=${bastion_public_ip} ansible_user=${vm_user} internal_ip=${bastion_internal_ip}

[web_servers]
%{ for server in web_servers ~}
${server.fqdn} ansible_host=${server.ip} ansible_user=${vm_user} zone=${server.zone}
%{ endfor ~}

[zabbix_server]
${zabbix_fqdn} ansible_host=${zabbix_public_ip} ansible_user=${vm_user} internal_ip=${zabbix_internal_ip}

[elasticsearch]
${elasticsearch_fqdn} ansible_host=${elasticsearch_internal_ip} ansible_user=${vm_user}

[kibana]
${kibana_fqdn} ansible_host=${kibana_public_ip} ansible_user=${vm_user} internal_ip=${kibana_internal_ip}

[monitoring_agents:children]
web_servers

[log_collection:children]
web_servers

[all_servers:children]
bastion
web_servers
zabbix_server
elasticsearch
kibana

[all_servers:vars]
ansible_ssh_private_key_file=~/.ssh/id_ed25519
ansible_ssh_common_args='-o StrictHostKeyChecking=no'