# Ansible inventory generated by Terraform
# Date: ${timestamp()}

all:
  vars:
    ansible_user: ${vm_user}
    ansible_ssh_private_key_file: ~/.ssh/id_ed25519
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

  children:
    bastion:
      hosts:
        ${bastion_fqdn}:

    web_servers:
      hosts:
%{ for server in web_servers ~}
        ${server.fqdn}:
          zone: ${server.zone}
%{ endfor ~}
      vars:
        nginx_port: 80
        zabbix_server: ${zabbix_internal_ip}
        elasticsearch_host: ${elasticsearch_internal_ip}

    zabbix_server:
      hosts:
        ${zabbix_fqdn}:
          zabbix_web_port: 80
          zabbix_server_port: 10051

    elasticsearch:
      hosts:
        ${elasticsearch_fqdn}:
          elasticsearch_port: 9200
          elasticsearch_cluster_name: diplom-cluster

    kibana:
      hosts:
        ${kibana_fqdn}:
          kibana_port: 5601

    monitoring_agents:
      children:
        web_servers

    log_collection:
      children:
        web_servers

    all_servers:
      children:
        bastion
        web_servers
        zabbix_server
        elasticsearch
        kibana